# Generated by Django 3.1 on 2023-10-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pictuire',
            new_name='profile_picture',
        ),
    ]
